DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cnt
    FROM (
        SELECT 1
        FROM WORKFLOWINBOX
        WHERE IDENTITYID IS NOT NULL
        GROUP BY PROCESSID, IDENTITYID
        HAVING COUNT(*) > 1
    );

    IF cnt > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'BREAKING CHANGES DETECTED: Duplicate PROCESSID and IDENTITYID values found in WORKFLOWINBOX table. Please contact support support@optimajet.com.');
    END IF;

    SELECT COUNT(*)
    INTO cnt
    FROM (
        SELECT 1
        FROM WORKFLOWPROCESSINSTANCEP
        GROUP BY PROCESSID, PARAMETERNAME
        HAVING COUNT(*) > 1
    );

    IF cnt > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'BREAKING CHANGES DETECTED: Duplicate PROCESSID and PARAMETERNAME values found in WORKFLOWPROCESSINSTANCEP table. Please contact support support@optimajet.com.');
    END IF;

    SELECT COUNT(*)
    INTO cnt
    FROM (
        SELECT 1
        FROM WORKFLOWPROCESSTIMER
        GROUP BY PROCESSID, NAME
        HAVING COUNT(*) > 1
    );

    IF cnt > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'BREAKING CHANGES DETECTED: Duplicate PROCESSID and NAME values found in WORKFLOWPROCESSTIMER table. Please contact support support@optimajet.com.');
    END IF;

    SELECT COUNT(*)
    INTO cnt
    FROM (
        SELECT 1
        FROM WORKFLOWGLOBALPARAMETER
        GROUP BY TYPE, NAME
        HAVING COUNT(*) > 1
    );

    IF cnt > 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'BREAKING CHANGES DETECTED: Duplicate TYPE and NAME values found in WORKFLOWGLOBALPARAMETER table. Please contact support support@optimajet.com.');
    END IF;
END;
/

DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cnt
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'WORKFLOWPROCESSINSTANCE'
        AND COLUMN_NAME = 'CALENDARNAME';

    IF cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKFLOWPROCESSINSTANCE ADD (CALENDARNAME NVARCHAR2(1024))';
    END IF;
END;
/

DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cnt
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IDX_CALENDARNAME';

    IF cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_CALENDARNAME ON WORKFLOWPROCESSINSTANCE (CALENDARNAME) LOGGING';
    END IF;
END;
/

DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cnt
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IDX_WORKFLOWINBOX_PI';

    IF cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_WORKFLOWINBOX_PI ON WORKFLOWINBOX (PROCESSID, IDENTITYID)';
    END IF;
END;
/

DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cnt
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IDX_WORKFLOWPROCESSINSTANCEP_PP';

    IF cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_WORKFLOWPROCESSINSTANCEP_PP ON WORKFLOWPROCESSINSTANCEP (PROCESSID, PARAMETERNAME)';
    END IF;
END;
/

DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cnt
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IDX_WORKFLOWPROCESSTIMER_PN';

    IF cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_WORKFLOWPROCESSTIMER_PN ON WORKFLOWPROCESSTIMER (PROCESSID, NAME)';
    END IF;
END;
/

DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cnt
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IDX_WORKFLOWGLOBALPARAMETER_TY';

    IF cnt > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX IDX_WORKFLOWGLOBALPARAMETER_TY';
    END IF;

    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_WORKFLOWGLOBALPARAMETER_TY ON WORKFLOWGLOBALPARAMETER (TYPE, NAME)';
END;
/

DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cnt
    FROM USER_TABLES
    WHERE TABLE_NAME = 'WORKFLOWFORM';

    IF cnt = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE WORKFLOWFORM (
                ID RAW(16) NOT NULL,
                NAME NVARCHAR2(512) NOT NULL,
                VERSION NUMBER(10) NOT NULL,
                CREATIONDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                UPDATEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                DEFINITION NCLOB NOT NULL,
                LOCKFLAG NUMBER(10) NOT NULL,
                CONSTRAINT PK_WORKFLOWFORM PRIMARY KEY (ID),
                CONSTRAINT UQ_WORKFLOWFORM_NAME_VERSION UNIQUE (NAME, VERSION)
            )
            LOGGING';
    END IF;
END;
/

DECLARE
    cnt NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cnt
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IDX_WORKFLOWPROCESSSCHEME_SCHE';

    IF cnt > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX IDX_WORKFLOWPROCESSSCHEME_SCHE';
    END IF;

    EXECUTE IMMEDIATE 'CREATE INDEX IDX_WORKFLOWPROCESSSCHEME_SCHE ON WORKFLOWPROCESSSCHEME (SCHEMECODE, ISOBSOLETE) LOGGING';
END;
/

ALTER TABLE WORKFLOWPROCESSSCHEME MODIFY (DEFININGPARAMETERSHASH NULL);
ALTER TABLE WORKFLOWPROCESSSCHEME MODIFY (DEFININGPARAMETERS NULL);

COMMIT;
